---
title: "R Notebook"
output: html_notebook
---

```{r}
library(lubridate)
library(dplyr)
```


```{r}
flightdf <- read.csv("finalflightdf.csv")
flightdf$X <- NULL
flightdf$Date <- ymd_hms(flightdf$Date, tz = "America/New_York")
```


```{r}
sn72 <- read.csv("sn72.csv")
sn72$X <- NULL
sn72$date <- ymd_hms(sn72$date)
```

# Method 2 (Short timeframes) revisited

```{r}

#create start time and end time for each datapoint in flight df (+/- 90 s)
flightdf$starttime <- flightdf$Date - 90
flightdf$endtime <- flightdf$Date + 90

#22L arrival and departure
A_22L <- flightdf %>%
  filter(Opr == "A", RW == "22L")

D_22L <- flightdf %>%
  filter(Opr == "D", RW == "22L")

#22R arrival and departure
A_22R <- flightdf %>%
  filter(Opr == "A", RW == "22R")

D_22R <- flightdf %>%
  filter(Opr == "D", RW == "22R")
```



```{r}

require(data.table) # v1.9.0+

sn72$date <- ymd_hms(sn72$date, tz="America/New_York")
A_22L$Date <- ymd_hms(A_22L$Date, tz="America/New_York")
A_22L$starttime <- ymd_hms(A_22L$starttime, tz="America/New_York")
A_22L$endtime <- ymd_hms(A_22L$endtime, tz="America/New_York")
#setnames(A_22L, old="Date", new="date")


setDT(A_22L) #makes df into datatable without wasting memory
setDT(sn72)
sn72[, dummy:=date]
A_22L <- A_22L[, !duplicated(colnames(A_22L))]
#setkey(mydata, DateTime1, DateTime2)
setkey(A_22L, starttime, endtime)
mydata2 <- foverlaps(sn72, A_22L, by.x=c("date", "dummy"), type ="within", nomatch=0L)[, dummy := NULL][]

```

#Method 1 (longer time frames) revisited

```{r}

library(dplyr)

hourlytally <- function(runwaystring){
  hourlyactivity <- flightdf %>%
  filter(RW == runwaystring) %>%
  mutate(hourly = format(date, format="%Y-%m-%d %H")) %>%
  group_by(hourly , Opr) %>%
  summarise(count = n() )
  
  # if hourly data is unique (no takeoffs AND landings) and Opr is A -> regime 2
  hourlyactivity$regimeflag <- ifelse(
    (
    (hourlyactivity$Opr %in% c("A")) &
     (duplicated(hourlyactivity$hourly)) == FALSE & ( duplicated(hourlyactivity$hourly, fromLast=TRUE) == FALSE  ) ),
  3,
    ifelse(
      (
   ( hourlyactivity$Opr %in% c("D")) &
   (duplicated(hourlyactivity$hourly)) == FALSE & ( duplicated(hourlyactivity$hourly, fromLast=TRUE) == FALSE  ) ),
      2,5 ))

  
  return(hourlyactivity)
}

hourly22L <- hourlytally("22L")
hourly22R <- hourlytally("22R")
hourly9 <- hourlytally("9")
hourly27 <- hourlytally("27")

```
```{r}
#create monthly column 
sn72$hourly <- format(sn72$date, format="%Y-%m-%d %H")

#merge datasets based on match of hourly  
reg2_72 <- merge(sn72, hourly22L, by = "hourly", all = FALSE)
```



