---
title: "Creating First Boxplots"

---

```{r}
library(data.table)
library(lubridate)
library(ggplot2)
library(dplyr)
library(stats)
```


```{r warning=FALSE}


sn45 <- fread("data/sn45filt.csv", sep = ",")
sn45$date <- ymd_hms(sn45$date, tz = "America/New_York")

sn49 <- fread("data/sn49filt.csv", sep = ",")
sn49$date <- ymd_hms(sn49$date, tz = "America/New_York")

sn62 <- fread("data/sn62filt.csv", sep = ",")
sn62$date <- ymd_hms(sn62$date, tz = "America/New_York")

sn67 <- fread("data/sn67filt.csv", sep = ",")
sn67$date <- ymd_hms(sn67$date, tz = "America/New_York")
```

# Final Plot # 2

```{r}
flightdf <- fread("data/finalflightdf.csv")
flightdf$Date <- ymd_hms(flightdf$Date , tz = "America/New_York")

 hourlyLTO <- flightdf %>%
   mutate(hourly = format(Date, format="%Y-%m-%d %H", tz = "America/New_York")) %>% #create datetime object that shows the hour
   group_by(hourly) %>% #group by hour 
   count(hourly, name = "num_flights")
# 
 LTOactivity <- subset(hourlyLTO, hourlyLTO$num_flights > 10)
```


```{r}
setDT(LTOactivity, key = "hourly")
setDT(hourlyLTO, key = "hourly")
```


```{r}
sn45O <- sn45
sn45N <- sn45

sn45O$filt <- ifelse(
    ( 
        (sn45O$wd > 170 & sn45O$wd < 240)                                   
    ),
    1,  # if condition is met, put 1
    0   # else put 0
)


sn45N$filt <-ifelse(
    ( 
        (sn45N$wd > 140 & sn45N$wd < 270)                                   
    ),
    1,  # if condition is met, put 1
    0   # else put 0
)
```


```{r}
sn45AvgO <- sn45O %>% 
  #dplyr::filter(.data$wd > 140 & .data$wd < 270) %>%
  dplyr::select(.data$co, .data$correctedNO, .data$no2model, .data$bin0, .data$date, .data$filt) %>%
  openair::timeAverage(avg.time = "1 hour", tz = "America/New_York") %>% 
  mutate(date = ymd_hms(.data$date, tz = "America/New_York")) %>% #timeAverage reverts to GMT
  mutate(hourly = format(date, format="%Y-%m-%d %H", tz = "America/New_York"))

sn45AvgN <- sn45N %>% 
  #dplyr::filter(.data$wd > 140 & .data$wd < 270) %>%
  dplyr::select(.data$co, .data$correctedNO, .data$no2model, .data$bin0, .data$date, .data$filt) %>%
  openair::timeAverage(avg.time = "1 hour", tz = "America/New_York") %>% 
  mutate(date = ymd_hms(.data$date, tz = "America/New_York")) %>% #timeAverage reverts to GMT
  mutate(hourly = format(date, format="%Y-%m-%d %H", tz = "America/New_York"))





setDT(sn45AvgO, key = "hourly")
sn45FO <- hourlyLTO[sn45AvgO, nomatch = 0]
sn45FO <- sn45FO[ !is.nan(sn45FO$correctedNO), ]

setDT(sn45AvgN, key = "hourly")
sn45FN <- hourlyLTO[sn45AvgN, nomatch = 0]
sn45FN <- sn45FN[ !is.nan(sn45FN$correctedNO), ]

```
```{r}

sn45FO <- na.omit(sn45FO)
sn45FN <- na.omit(sn45FN)

stats::cor(x = sn45FO$num_flights, sn45FO$co, method = "pearson")
cor(sn45FO$num_flights, sn45FO$correctedNO, method = "pearson")
cor(sn45FO$num_flights, sn45FO$no2model, method = "pearson")

cor(sn45FN$num_flights, sn45FN$co, method = "pearson")
cor(sn45FN$num_flights, sn45FN$correctedNO, method = "pearson")
cor(sn45FN$num_flights, sn45FN$no2model, method = "pearson")
```
### With Depatures Only 
```{r}
sn45flightsT <- flightdf %>%
    filter(flightdf$RW == "22R" & flightdf$Opr == "D") %>%
    mutate(hourly = format(Date, format="%Y-%m-%d %H", tz = "America/New_York")) %>% #create datetime object that shows the hour
    group_by(hourly) %>% #group by hour 
    count(hourly, name = "num_flights") %>% 
    subset(num_flights > 10)

setDT(sn45flightsT, key = "hourly")
sn45F3 <- sn45AvgO[sn45flightsT, nomatch = 0]
sn45F4 <- sn45AvgN[sn45flightsT, nomatch = 0]

sn45F3 <- na.omit(sn45F3)
sn45F4 <- na.omit(sn45F4)

sn45F3 <- sn45F3[ !is.nan(sn45F3$correctedNO), ]
sn45F4 <- sn45F4[ !is.nan(sn45F4$correctedNO), ]

stats::cor(x = sn45F3$num_flights, sn45F3$co, method = "pearson")
cor(sn45F3$num_flights, sn45F3$correctedNO, method = "pearson")
cor(sn45F3$num_flights, sn45F3$no2model, method = "pearson")

cor(sn45F4$num_flights, sn45F4$co, method = "pearson")
cor(sn45F4$num_flights, sn45F4$correctedNO, method = "pearson")
cor(sn45F4$num_flights, sn45F4$no2model, method = "pearson")
```

# Final GRaph 1 

```{r}

# (aes(y = value, x = as.factor(filt), fill = as.factor(filt)),data=sn45LDF) + geom_boxplot(na.rm = TRUE, coef = 0.00000000000000000000000000000000000001) + facet_wrap(sn45LDF$variable, scales = "free", nrow = 3) + 
#   theme(legend.position="bottom",
#         legend.spacing.x = unit(0, 'cm'))
# ggplot(aes(y = value, x = as.factor(filt), fill = as.factor(filt)),data=sn45LDF) + geom_boxplot(na.rm = TRUE, notch = TRUE) + facet_wrap(sn45LDF$variable, scales = "free", nrow = 3) + 
#   theme(legend.position="bottom",
#         legend.spacing.x = unit(0, 'cm'))

y <- rnorm(100)
sn = sn45
iqr = quantile(sn45$co[sn$filt == 0], 3/4) - quantile(sn45$co[sn$filt == 0], 1/4) 
w = quantile(sn$co[sn$filt == 0], probs=c(.25, .75), na.rm = TRUE)
df <- data.frame(
  x = 1,
  
  y0 = (w[1]-1.5*iqr),
  y25 = w[1],
  y50 = median(sn$co[sn$filt == 0]),
  y75 = w[2],
  y100 = (w[2]+1.5*iqr)
)



library(cowplot) 
require(gridExtra)
  
plot1 <- ggplot(df, aes(x)) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity"
 ) +  labs(x = "New x label") + ylab("CO Concentration (ppb)") +
  theme(
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
  
plot2 <- ggplot(df, aes(x)) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity"
 ) +  labs(x = "New x label") + ylab("CO Concentration (ppb)") +
  theme(
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
#grid.arrange(plot1, plot2, ncol=2)

cowplot::plot_grid(plot1, plot2, ncol = 2, labels = c("Narrow Wind Range", "Wide Wind Range"))
```

```{r}
elim_outliers <- function(sn){
  quantile(sn45$co, 3/4) - quantile(sn45$co, 1/4)
  Q2 <- quantile(sn$co[sn$filt == 0], probs=c(.25, .75), na.rm = TRUE)
  Q3 <- quantile(sn$co[sn$filt == 1], probs=c(.25, .75), na.rm = TRUE)
}
```


```{r}
sn45$hourly = format(sn45$date, format="%Y-%m-%d %H", tz = "America/New_York")
setDT(sn45, key = "hourly")
sn45 <- LTOactivity[sn45, nomatch = 0]
iqrCO1 <- IQR(sn45$co[sn45$filt == 0])
iqrCO2 <- IQR(sn45$co[sn45$filt == 1])

iqrno1 <- IQR(sn45$corrrectedNO[sn45$filt == 0])
iqrno2 <- IQR(sn45$corrrectedNO[sn45$filt == 1])

eliminated<- subset(sn45, sn45$co > (Q[1] - 1.5*iqr) & warpbreaks$breaks < (Q[2]+1.5*iqr))
```

```{r}
iqr1 = quantile(sn45$co[sn$filt == 0], 3/4) - quantile(sn45$co[sn$filt == 0], 1/4) 
w1 = quantile(sn$co[sn$filt == 0], probs=c(.25, .75), na.rm = TRUE)

iqr2 = quantile(sn45$co[sn$filt == 1], 3/4) - quantile(sn45$co[sn$filt == 1], 1/4) 
w2 = quantile(sn$co[sn$filt == 1], probs=c(.25, .75), na.rm = TRUE)

df <- data.frame(
  x = c(1,2),
  
  y0 = c((w1[1]-1.5*iqr1), (w2[1]-1.5*iqr2) ), 
  y25 = c(w1[1], w2[1]), 
  y50 = c(median(sn$co[sn$filt == 0]), median(sn$co[sn$filt == 1]) ), 
  y75 = c(w1[2], w2[2]), 
  y100 = c((w1[2]+1.5*iqr1), (w2[2]+1.5*iqr2))
)


  
plot1 <- ggplot(df, aes(x, group = x, fill = as.factor(x))) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity"
 ) +  labs(x = "New x label") + ylab("CO Concentration (ppb)") +
  theme(
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

plot1
```

```{r}
makeplotgood <- function(sn, sn2){
iqr1 = quantile(sn$co[sn$filt == 0], 3/4 , na.rm = TRUE) - quantile(sn$co[sn$filt == 0], 1/4 , na.rm = TRUE) 
w1 = quantile(sn$co[sn$filt == 0], probs=c(.25, .75), na.rm = TRUE)

iqr2 = quantile(sn$co[sn$filt == 1], 3/4 , na.rm = TRUE) - quantile(sn$co[sn$filt == 1], 1/4 , na.rm = TRUE) 
w2 = quantile(sn$co[sn$filt == 1], probs=c(.25, .75), na.rm = TRUE)

iqr3 = quantile(sn2$co[sn$filt == 0], 3/4 , na.rm = TRUE) - quantile(sn2$co[sn$filt == 0], 1/4 , na.rm = TRUE) 
w3 = quantile(sn2$co[sn$filt == 0], probs=c(.25, .75), na.rm = TRUE)

iqr4 = quantile(sn2$co[sn$filt == 1], 3/4 , na.rm = TRUE) - quantile(sn2$co[sn$filt == 1], 1/4 , na.rm = TRUE) 
w4 = quantile(sn2$co[sn$filt == 1], probs=c(.25, .75), na.rm = TRUE)

df <- data.frame(
  x = c(1,2,3,4),
  x2 = c(c(1,2), c(3,4)),
  
  y0 = c((w1[1]-1.5*iqr1), (w2[1]-1.5*iqr2) , (w3[1]-1.5*iqr3), (w4[1]-1.5*iqr4) ), 
  y25 = c(w1[1], w2[1], w3[1], w4[1]), 
  y50 = c(median(sn$co[sn$filt == 0], na.rm = TRUE), median(sn$co[sn$filt == 1], na.rm = TRUE), 
          median(sn2$co[sn2$filt == 0], na.rm = TRUE), median(sn2$co[sn2$filt == 1], na.rm = TRUE)),  
  y75 =  c(w1[2], w2[2], w3[2], w4[2]), 
  y100 = c((w1[2]+1.5*iqr1), (w2[2]+1.5*iqr2) , (w3[2]+1.5*iqr3), (w4[2]+1.5*iqr4) )
)

return(df)
}



makeplotgoodNO <- function(sn, sn2){
iqr1 = quantile(sn$correctedNO[sn$filt == 0], 3/4 , na.rm = TRUE) - quantile(sn$correctedNO[sn$filt == 0], 1/4, na.rm = TRUE) 
w1 = quantile(sn$correctedNO[sn$filt == 0], probs=c(.25, .75), na.rm = TRUE)

iqr2 = quantile(sn$correctedNO[sn$filt == 1], 3/4, na.rm = TRUE) - quantile(sn$correctedNO[sn$filt == 1], 1/4, na.rm = TRUE) 
w2 = quantile(sn$correctedNO[sn$filt == 1], probs=c(.25, .75), na.rm = TRUE)

iqr3 = quantile(sn2$correctedNO[sn$filt == 0], 3/4, na.rm = TRUE) - quantile(sn2$correctedNO[sn$filt == 0], 1/4, na.rm = TRUE) 
w3 = quantile(sn2$correctedNO[sn$filt == 0], probs=c(.25, .75), na.rm = TRUE)

iqr4 = quantile(sn2$correctedNO[sn$filt == 1], 3/4, na.rm = TRUE) - quantile(sn2$correctedNO[sn$filt == 1], 1/4, na.rm = TRUE) 
w4 = quantile(sn2$correctedNO[sn$filt == 1], probs=c(.25, .75), na.rm = TRUE)

df <- data.frame(
  x = c(1,2,3,4),
  x2 = c(c(1,2), c(3,4)),
  
  y0 = c((w1[1]-1.5*iqr1), (w2[1]-1.5*iqr2) , (w3[1]-1.5*iqr3), (w4[1]-1.5*iqr4) ), 
  y25 = c(w1[1], w2[1], w3[1], w4[1]), 
  y50 = c(median(sn$correctedNO[sn$filt == 0], na.rm = TRUE), median(sn$correctedNO[sn$filt == 1], na.rm = TRUE), 
          median(sn2$correctedNO[sn2$filt == 0], na.rm = TRUE), median(sn2$correctedNO[sn2$filt == 1], na.rm = TRUE)),  
  y75 =  c(w1[2], w2[2], w3[2], w4[2]), 
  y100 = c((w1[2]+1.5*iqr1), (w2[2]+1.5*iqr2) , (w3[2]+1.5*iqr3), (w4[2]+1.5*iqr4) )
)

return(df)
}

makeplotgoodNO2 <- function(sn, sn2){
iqr1 = quantile(sn$no2model[sn$filt == 0], 3/4 , na.rm = TRUE) - quantile(sn$no2model[sn$filt == 0], 1/4, na.rm = TRUE) 
w1 = quantile(sn$no2model[sn$filt == 0], probs=c(.25, .75), na.rm = TRUE)

iqr2 = quantile(sn$no2model[sn$filt == 1], 3/4, na.rm = TRUE) - quantile(sn$no2model[sn$filt == 1], 1/4, na.rm = TRUE) 
w2 = quantile(sn$no2model[sn$filt == 1], probs=c(.25, .75), na.rm = TRUE)

iqr3 = quantile(sn2$no2model[sn$filt == 0], 3/4, na.rm = TRUE) - quantile(sn2$no2model[sn$filt == 0], 1/4, na.rm = TRUE) 
w3 = quantile(sn2$no2model[sn$filt == 0], probs=c(.25, .75), na.rm = TRUE)

iqr4 = quantile(sn2$no2model[sn$filt == 1], 3/4, na.rm = TRUE) - quantile(sn2$no2model[sn$filt == 1], 1/4, na.rm = TRUE) 
w4 = quantile(sn2$no2model[sn$filt == 1], probs=c(.25, .75), na.rm = TRUE)

df <- data.frame(
  x = c(1,2,3,4),
  x2 = c(c(1,2), c(3,4)),
  
  y0 = c((w1[1]-1.5*iqr1), (w2[1]-1.5*iqr2) , (w3[1]-1.5*iqr3), (w4[1]-1.5*iqr4) ), 
  y25 = c(w1[1], w2[1], w3[1], w4[1]), 
  y50 = c(median(sn$no2model[sn$filt == 0], na.rm = TRUE), median(sn$no2model[sn$filt == 1], na.rm = TRUE), 
          median(sn2$no2model[sn2$filt == 0], na.rm = TRUE), median(sn2$no2model[sn2$filt == 1], na.rm = TRUE)),  
  y75 =  c(w1[2], w2[2], w3[2], w4[2]), 
  y100 = c((w1[2]+1.5*iqr1), (w2[2]+1.5*iqr2) , (w3[2]+1.5*iqr3), (w4[2]+1.5*iqr4) )
)

return(df)
}
```


```{r}
sn45_2 <- sn45
sn45$filt <- ifelse(
    ( 
        (sn45$wd > 170 & sn45$wd < 240)                                   
    ),
    1,  # if condition is met, put 1
    0   # else put 0
) 
sn45_2$filt <- ifelse(
    ( 
        (sn45$wd > 140 & sn45$wd < 270)                                   
    ),
    1,  # if condition is met, put 1
    0   # else put 0
)

goodf.45 <- makeplotgood(sn45, sn45_2)
goodf2.45 <- makeplotgoodNO(sn45, sn45_2)
goodf3.45 <- makeplotgoodNO2(sn45, sn45_2)
```

```{r}
#pdf("sn45-boxplots.pdf")
 ggplot(goodf.45, aes(x, group = x2, fill = factor(x, labels=c("Narrow Upwind","Narrow Downwind", "Wide Upwind","Wide Downwind")))) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity"
 ) +  labs(title = "Co Concentrations Upwind vs Downwind on Site 45", fill = "Regimes") + ylab("CO Concentration (ppb)") + 
  theme(axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

 ggplot(goodf2.45, aes(x, group = x2, fill = factor(x, labels=c("Narrow Upwind","Narrow Downwind", "Wide Upwind","Wide Downwind")))) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity"
 ) +  labs(title = "NO Concentrations Upwind vs Downwind on Site 45", fill = "Regimes") + ylab("NO Concentration (ppb)") + 
  theme(axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
 
  ggplot(goodf3.45, aes(x, group = x2, fill = factor(x, labels=c("Narrow Upwind","Narrow Downwind", "Wide Upwind","Wide Downwind")))) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity"
 ) +  labs(title = "No2 Concentrations Upwind vs Downwind on Site 45", fill = "Regimes") + ylab("NO2 Concentration (ppb)") + 
  theme(axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
  
#dev.off()
```

# SN 67
```{r}
library(data.table)
sn67 <- fread("data/sn67filt.csv", sep = ",")
sn67$date <- ymd_hms(sn67$date, tz = "America/New_York") 

sn67_2 <- sn67
sn67$filt <- ifelse(
    ( 
        (sn67$wd > 240 & sn67$wd < 300)                                   
    ),
    1,  # if condition is met, put 1
    0   # else put 0
) 
sn67_2$filt <- ifelse(
  #wd: 240-300 degrees
  #wd: 200-330 degrees
    ( 
        (sn67$wd > 200 & sn67$wd < 330)                                   
    ),
    1,  # if condition is met, put 1
    0   # else put 0
)

goodf <- makeplotgood(sn67, sn67_2)
goodf2 <- makeplotgoodNO(sn67, sn67_2)
goodf3 <- makeplotgoodNO2(sn67, sn67_2)
```


```{r}
library(ggplot2)
#pdf("finalplot.pdf")
 ggplot(goodf2, aes(x, group = x2, fill = factor(x, labels=c("Narrow Upwind","Narrow Downwind", "Wide Upwind","Wide Downwind")))) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity"
 ) +  labs(title = "NO Concentrations Upwind vs Downwind on Site 45", fill = "Regimes") + ylab("NO Concentration (ppb)") + 
  theme(axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(), 
         axis.title.y= element_text(size = 12), 
        axis.text.y= element_text(size = 11)) +
   
theme(plot.title = element_text(size = 16, face = "bold"),
    legend.title=element_text(size=14), 
    legend.text=element_text(size=13))

ggsave("finalplot.pdf")
 
#dev.off()
```
```{r}
 ggplot(goodf2, aes(x, group = x2, fill = factor(x))) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity",  show.legend = FALSE
 ) +  labs(title = "NO Concentrations Upwind vs Downwind on Site 45") + ylab("NO Concentration (ppb)") + 
  theme(axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(), 
         axis.title.y= element_text(size = 12), 
        axis.text.y= element_text(size = 11), 
        legend.title = element_blank(), 
        legend.text = element_blank()) 

ggsave("finalplot2.pdf")
```

