---
title: "R Notebook"
output: html_notebook
---

hello world

In this notebook, I try coding the two regime methods that Scott and I talked about. 

```{r}
library(readxl)
library(plyr)
library(lubridate)
```


# Setup 

I accidentally deleted one of my function to make the flightdf from last time, so here I put the code together again.  

```{r}
#importing 2020 data
lst <- lapply(1:3, function(i) read_excel("Summer2020/OlinFebruaryApril2020dataset.xlsx", sheet = i))
flightdf2020 <- ldply(lst, data.frame)
#formatting datetime
flightdf2020$Time <- format(flightdf2020$Time,"%H:%M:%S")
flightdf2020$Date <- with(flightdf2020, ymd(Date) + hms(Time), tz = "America/New_York") #combining and setting timezone
flightdf2020$Time <- NULL

#importing 2019 data 
flightdf1 = read.csv("Summer2020/Olin2019dataset.csv", header=TRUE, fileEncoding="UTF-8-BOM")
#formatting datetime
flightdf1$Date <- with(flightdf1, mdy(Date) + hms(Time), tz = "America/New_York") #combining and setting timezone
flightdf1$Time <- NULL #deleting the time column

flightdf <- rbind(flightdf1, flightdf2020) #merging

write.csv(flightdf, "finalflightdf.csv")
flightdf <- read.csv("finalflightdf.csv")
flightdf$X <- NULL
flightdf$Date <- ymd_hms(flightdf$Date)


```


I'll also importing the dataframes as well 

```{r}

source("importalldatacsv.R")
sn72 <- read.csv("sn72.csv")
sn72$X <- NULL
sn72$date <- ymd_hms(sn72$date)

```

# Method 1

```{r}

detach("package:plyr", unload=TRUE) 
library(dplyr)

hourlytally <- function(runwaystring){
  hourlyactivity <- flightdf %>%
  filter(RW == runwaystring) %>%
  #mutate(originaldate = Date) %>%
  mutate(hourly = format(Date, format="%Y-%m-%d %H")) %>%
  group_by(hourly , Opr) %>%
  summarise(count = n() )
  
  # if hourly data is unique (no takeoffs AND landings) and Opr is A -> regime 2
  hourlyactivity$regimeflag <- ifelse(
    (
    (hourlyactivity$Opr %in% c("A")) &
     (duplicated(hourlyactivity$hourly)) == FALSE & ( duplicated(hourlyactivity$hourly, fromLast=TRUE) == FALSE  ) ),
  3,
    ifelse(
      (
   ( hourlyactivity$Opr %in% c("D")) &
   (duplicated(hourlyactivity$hourly)) == FALSE & ( duplicated(hourlyactivity$hourly, fromLast=TRUE) == FALSE  ) ),
      2,5 ))

  
  return(hourlyactivity)
}

hourlyactivityrunway22L <- hourlytally("22L")
hourlyactivityrunway22R <- hourlytally("22R")
hourlyactivityrunway9 <- hourlytally("9")
hourlyactivityrunway27 <- hourlytally("27")




```
```{r}

```


# Method 2

```{r}

#create start time and end time for each datapoint in flight df (+/- 90 s)
flightdf$starttime <- flightdf$Date - 90
flightdf$endtime <- flightdf$Date + 90

#22L arrival and departure
A_22L <- flightdf %>%
  filter(Opr == "A", RW == "22L")

D_22L <- flightdf %>%
  filter(Opr == "D", RW == "22L")

#22R arrival and departure
A_22R <- flightdf %>%
  filter(Opr == "A", RW == "22R")

D_22R <- flightdf %>%
  filter(Opr == "D", RW == "22R")

library(fuzzyjoin)

#take sensor data, filter if it is between any start times and end times 
sn72_reg2 <- sn72 %>%
  filter(Date > D_22L$starttime & Date < D_22L$endtime)

D_22L$starttime <- ymd_hms(D_22L$starttime)
D_22L$endtime <- ymd_hms(D_22L$endtime)

sn72_reg2 <- fuzzy_left_join(sn72, D_22L, 
               by = c("Date" = "starttime", "Date" = "endtime"), 
               match_fun = list(`>=`, `<=`))

sn72_reg3 <- sn72 %>%
  filter(Date > A_22L$starttime & Date < A_22L$endtime)

sn72_reg1 <- sn72 %>% 
  filter(Date > flightdf$starttime & Date < flightdf$endtime, 
         wd > 180 & wd < 240)

sn72_reg4 <- sn72[!(sn72$date %in% c(sn72_reg1$date, sn72_reg2$date, sn72_reg3$date)),]

```

