---
title: "R Notebook"
output: html_notebook
---

TO EXPLORE

 - WEIRD OUTPUT FROM D45 AFTER MIXTRING WITH CORRELATION FUNCTION 


TO ADD

 - NICE TITLES TO PLOTS FOR READABILITY

 - R2 ANALYSIS


Redoing the comparisons of devices and downloaded data again, here with proper functions

necesarry packages
```{r}

library(readr)
library(lubridate)


```

loading and cleaning official downloaded boston data, also creating a hourly averaged data frame, bos.h
```{r}
bos <- read_csv("bos_190226-200226_knot_dir_EDT.csv") 

bos <- bos %>% select(c("valid",
                          "drct", 
                          "sknt")) 


names(bos)[names(bos) == "valid"] <- "timestamp_local"
names(bos)[names(bos) == "drct"] <- "wd"
names(bos)[names(bos) == "sknt"] <- "wskn"

# adding wind speed vector in m/s, from knot in initial downloaded data
bos$ws = bos$wskn*0.5144444 

# for some reason ( csv format? ) bos is reverse order, fixing that
bos$timestamp_local <- rev(bos$timestamp_local)
bos$wind_dir <- rev(bos$wd)
bos$wind_speed <- rev(bos$wskn)
bos$wind_speed_ms <- rev(bos$ws)


# for some reason the wind dir is of charachter type
bos$wd <- as.numeric(bos$wd)

# appropriate timezone
tz(bos$timestamp_local) <- "EST" 

# final rough clean
bos <- wind_clean(bos)

# averaged hourly data frame
bos.h <- hour_mean(bos)


```


device 45
```{r}
#loading data, merging raw and final
d45 <- get_device("d45_190226-200226_raw.csv","d45_190226-200226_final.csv","d45")

# rough clean, too high/low wind speed values and wind dir not within 0-360 
d45 <- wind_clean(d45)

# 5 min analysis
d45.5 <- average_by(d45, by = "5 minutes")

d45.5_bos <- dev_down_merge(d45.5,bos)

correlation(d45.5_bos)

# hourly analysis
d45.h <- hour_mean(d45)

d45.h_bos.h <- dev_down_merge(d45.h, bos.h) 

correlation(d45.h_bos.h)

```









