---
title: "R Notebook"

---

```{r, message = FALSE, warning=FALSE}
source("cpc.R")
main_path <- "C:/Users/abusa/Documents/GitHub/EB_AQ_Network/Fall2020/data/new_cpc_data"
aeth_path <- paste0(main_path, "/AETHLOMETER")
sn45_path <- paste0(main_path, "/sn45_cpc.csv")
sn46_path <- paste0(main_path, "/sn46_cpc.csv")
cpc_path <- paste0(main_path, "/MCPC data")

fulldtst <- generate_comparison(aeth_path, cpc_path, sn45_path, sn46_path)
```

```{r}
library(openair)
library(corrplot)
corrplot(fulldtst[, c("concent","UV BC1", "no", "no2", "co", "co2")], method = "number", na.rm = TRUE)
fulldtst_omit <- na.omit(fulldtst)
cor(fulldtst_omit[, c("concent","UV BC1", "no", "no2", "co", "co2")])
```
```{r}
  nm <- list.files(path=cpc_path, all.files = TRUE, full.names = TRUE, pattern="*.TXT")
  
  cpc_upload <- do.call(rbind, lapply(nm, function(x) read.delim(file=x, header = TRUE, skip = 13) ) )
  
  ## removing unncessary variables 
  
  cpc_upload <- cpc_upload[ , c("X.YY.MM.DD", "HR.MN.SC", "concent", "fillcnt"  )]
  
  ##formatting datetime
  
  cpc_upload$date <- with(cpc_upload, ymd(`X.YY.MM.DD`) + hms(`HR.MN.SC`))
  
  tz(cpc_upload$date) <- "America/New_York"
  
  #hour(cpc_upload$date) <- hour(cpc_upload$date) + 8 
  
  # cpc_upload$binary_fillcnt <- ifelse(
  #   ( 
  #     (cpc_upload$fillcnt != 0 )
  #   ),
  #   1,  # if condition is met, put 1
  #   0   # else put 0
  # )
  
  if(cpc_upload$concent == 0){
    cpc_upload[which(cpc_upload$concent == 0), concent] <- NA
  }
```

```{r}
sum(cpc_upload$concent == 0) 
```



```{r}
#timePlot(fulldtst, pollutant = c("concent","UV BC1", "Blue BC1", "Green BC1", "Red BC1", "IR BC1",
#                                "no2",  "i.no2", "no", "i.no","co",  "i.co",  "co2",
#                               "i.co2"), y.relation = "free", main = "SN 45 SN 46 Aeth Week 1")



timePlot(fulldtst, pollutant = c("concent","UV BC1",
                                "no", "no2", "co",   "co2"), y.relation = "free", main = "one BC var, SN45 and CPC - Full Timescale",
                                ylab = "", key = FALSE) 

timePlot(fulldtst, pollutant = c("concent","UV BC1", "Blue BC1", "Green BC1", "Red BC1", "IR BC1",
                                "no", "no2", "co",   "co2"), y.relation = "free", main = "all BC vars, SN45 and CPC - Full Timescale",
                                ylab = "", key = FALSE)


```





