---
title: "New Regime Boxplots"
---

# Motivation 

We will test out the new downwind/upwind definitions by creating boxplots. We will use the new boxplot code I generated in the summer 

# Import 

```{r message=FALSE, warning=FALSE}
library(lubridate)
library(openair)
library(data.table)
library(dplyr)
library(baseline)
library(Rmisc)
library(ggplot2)
```

```{r}

sn45_dw1<- fread(paste("data/","sn45", "_dw1.csv", sep ="") ,header= TRUE)
sn45_dw2<-fread(paste("data/","sn45", "_dw2.csv", sep ="") ,header= TRUE)
sn45_uw<-fread(paste("data/","sn45", "_uw.csv", sep ="") ,header= TRUE)

sn49_dw1 <-fread(paste("data/","sn49", "_dw1.csv", sep ="") ,header= TRUE)
sn49_dw2 <-fread(paste("data/","sn49", "_dw2.csv", sep ="") ,header= TRUE)
sn49_uw<-fread(paste("data/","sn49", "_uw.csv", sep ="") ,header= TRUE)

sn62_dw1<-fread(paste("data/","sn62", "_dw1.csv", sep ="") ,header= TRUE)
sn62_dw2<-fread(paste("data/","sn62", "_dw2.csv", sep ="") ,header= TRUE)
sn62_uw<-fread(paste("data/","sn62", "_uw.csv", sep ="") ,header= TRUE)

sn67_dw1<-fread(paste("data/","sn67", "_dw1.csv", sep ="") ,header= TRUE)
sn67_dw2<-fread(paste("data/","sn67", "_dw2.csv", sep ="") ,header= TRUE)
sn67_uw<-fread(paste("data/","sn67", "_uw.csv", sep ="") ,header= TRUE)



```


# Boxplot Code 

## Trying standard boxplot code 

```{r}
#boxplot(c(sn45_dw1$co, sn45_dw2$co, sn45_uw$co) ,names = c("ozone", "normal", "temp"))
```

## Trying Previous Function 



```{r}
sn_prep_plot <- function(sndw1, sndw2, snuw){
  sndw1.melt <- melt(sndw1, id.vars=c("date"), measure.vars = c( "co", "no2model", "correctedNO"))
  sndw2.melt <- melt(sndw2, id.vars=c("date"), measure.vars = c( "co", "no2model", "correctedNO"))
  snuw.melt <- melt(snuw, id.vars=c("date"), measure.vars = c( "co", "no2model", "correctedNO"))
  
  sndw1.melt$reg <- rep("dw1", nrow(sndw1.melt))
  sndw2.melt$reg <- rep("dw2", nrow(sndw2.melt))
  snuw.melt$reg <- rep("uw", nrow(snuw.melt))
  
  sn_total <- rbind(sndw1.melt, sndw2.melt, snuw.melt)
  
  return(sn_total)
}
```

```{r}
sn45_bp <- sn_prep_plot(sn45_dw1, sn45_dw2, sn45_uw)
```


```{r}
ggplot(aes(y = value, x = reg, fill = as.factor(reg)),data=sn45_bp) + geom_violin(na.rm = TRUE) + facet_wrap(sn45_bp$variable, scales = "free") + 
  theme(legend.position="bottom",
        legend.spacing.x = unit(0, 'cm'))
```
```{r}
ggplot(aes(y = value, x = reg, fill = as.factor(reg)),data=sn45_bp) + geom_boxplot(na.rm = TRUE) + facet_wrap(sn45_bp$variable, scales = "free") + 
  theme(legend.position="bottom",
        legend.spacing.x = unit(0, 'cm'))
```


## Trying custom function


```{r}
prepare_boxplot <- function(sndw1, sndw2, snuw){
  
  # CO 
  codf <- data.frame(
    #x2 = c(c(1,2), c(3,4)),
  
  y0 <- rep(NA, 3), 
  y25 <- rep(NA, 3), 
  y50 <- rep(NA, 3), 
  y100 <- rep(NA, 3)
)
  
  i = 1
  for(sn in list(sndw1, sndw2, snuw)){
    iqr1 <- quantile(sn$co, 3/4 , na.rm = TRUE) - quantile(sn$co, 1/4, na.rm = TRUE) 
    w1 <- quantile(sn$co, probs=c(.25, .75), na.rm = TRUE)
    
    codf$y0[i] <- w1[[1]]-1.5*iqr1[[1]]

    codf$y25[i] <- w1[[1]]

    codf$y50[i] <- median(sn$co, na.rm = TRUE)
    codf$y75[i] <- w1[[2]]
    codf$y100[i] <-w1[[2]]+1.5*iqr1[[1]]
    i <- i+ 1
  }
  
  codf$x <- c(1,2,3)
  
  # NO 
  
    nodf <- data.frame(
    #x2 = c(c(1,2), c(3,4)),
  
  y0 <- rep(NA, 3), 
  y25 <- rep(NA, 3), 
  y50 <- rep(NA, 3), 
  y100 <- rep(NA, 3)
)
  
  i = 1
  for(sn in list(sndw1, sndw2, snuw)){
    iqr1 <- quantile(sn$correctedNO, 3/4 , na.rm = TRUE) - quantile(sn$correctedNO, 1/4, na.rm = TRUE) 
    w1 <- quantile(sn$correctedNO, probs=c(.25, .75), na.rm = TRUE)
    
    nodf$y0[i] <- w1[[1]]-1.5*iqr1[[1]]

    nodf$y25[i] <- w1[[1]]

    nodf$y50[i] <- median(sn$correctedNO, na.rm = TRUE)
    nodf$y75[i] <- w1[[2]]
    nodf$y100[i] <-w1[[2]]+1.5*iqr1[[1]]
    i <- i+ 1
  }
  
  nodf$x <- c(1,2,3)
  
  # NO2
  
    no2df <- data.frame(
    #x2 = c(c(1,2), c(3,4)),
  
  y0 <- rep(NA, 3), 
  y25 <- rep(NA, 3), 
  y50 <- rep(NA, 3), 
  y100 <- rep(NA, 3)
)
  
  i = 1
  for(sn in list(sndw1, sndw2, snuw)){
    iqr1 <- quantile(sn$no2model, 3/4 , na.rm = TRUE) - quantile(sn$no2model, 1/4, na.rm = TRUE) 
    w1 <- quantile(sn$no2model, probs=c(.25, .75), na.rm = TRUE)
    
    no2df$y0[i] <- w1[[1]]-1.5*iqr1[[1]]

    no2df$y25[i] <- w1[[1]]

    no2df$y50[i] <- median(sn$no2model, na.rm = TRUE)
    no2df$y75[i] <- w1[[2]]
    no2df$y100[i] <-w1[[2]]+1.5*iqr1[[1]]
    i <- i+ 1
  }
  
  no2df$x <- c(1,2,3)

  return(list("codf"= codf, "nodf" = nodf, "no2df" = no2df))
}
```

```{r}
sn45_df <- prepare_boxplot(sn45_dw1, sn45_dw2, sn45_uw)
```




```{r}
#pdf("finalplot.pdf")
 ggplot(sn45_df$codf, aes(x,  fill = factor(x, labels=c("low winds", "high winds DW", "upwind")))) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity"
 ) +  labs(title = "CO Concentrations Upwind vs Downwind on Site 45", fill = "Regimes") + ylab("CO Concentration (ppb)") + 
  theme(axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(), 
         axis.title.y= element_text(size = 12), 
        axis.text.y= element_text(size = 11)) +
   
theme(plot.title = element_text(size = 16, face = "bold"),
    legend.title=element_text(size=14), 
    legend.text=element_text(size=13))

#ggsave("finalplot.pdf")
```


```{r}
 ggplot(sn45_df$nodf, aes(x,  fill = factor(x, labels=c("low winds", "high winds DW", "upwind")))) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity"
 ) +  labs(title = "NO Concentrations Upwind vs Downwind on Site 45", fill = "Regimes") + ylab("CO Concentration (ppb)") + 
  theme(axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(), 
         axis.title.y= element_text(size = 12), 
        axis.text.y= element_text(size = 11)) +
   
theme(plot.title = element_text(size = 16, face = "bold"),
    legend.title=element_text(size=14), 
    legend.text=element_text(size=13))
```
```{r}
 ggplot(sn45_df$no2df, aes(x,  fill = factor(x, labels=c("low winds", "high winds DW", "upwind")))) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity"
 ) +  labs(title = "NO2 Concentrations Upwind vs Downwind on Site 45", fill = "Regimes") + ylab("CO Concentration (ppb)") + 
  theme(axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(), 
         axis.title.y= element_text(size = 12), 
        axis.text.y= element_text(size = 11)) +
   
theme(plot.title = element_text(size = 16, face = "bold"),
    legend.title=element_text(size=14), 
    legend.text=element_text(size=13))
```

